
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package fr.ul.miage.expression;

/** CUP generated interface containing symbol constants. */
public interface Sym {
  /* terminals */
  public static final int RETOURNE = 18;
  public static final int IDF = 11;
  public static final int GLOB = 12;
  public static final int SUP = 22;
  public static final int LIRE = 17;
  public static final int ECRIRE = 16;
  public static final int TANTQUE = 19;
  public static final int AFF = 8;
  public static final int INF = 23;
  public static final int AO = 6;
  public static final int NUM = 9;
  public static final int SINON = 21;
  public static final int PO = 4;
  public static final int ENTIER = 14;
  public static final int EOF = 0;
  public static final int AF = 7;
  public static final int ADD = 2;
  public static final int PROG = 10;
  public static final int SI = 20;
  public static final int error = 1;
  public static final int PF = 5;
  public static final int VIDE = 15;
  public static final int PARAM = 13;
  public static final int MUL = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ADD",
  "MUL",
  "PO",
  "PF",
  "AO",
  "AF",
  "AFF",
  "NUM",
  "PROG",
  "IDF",
  "GLOB",
  "PARAM",
  "ENTIER",
  "VIDE",
  "ECRIRE",
  "LIRE",
  "RETOURNE",
  "TANTQUE",
  "SI",
  "SINON",
  "SUP",
  "INF"
  };
}

